- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}'."
  ansible.builtin.assert:
    that:
      - prev_number is defined
      - first_number is defined
      - second_number is defined
      - sql_file is defined
      - sql_file | length > 0
      - file_path is defined
      - file_path | length > 0
    fail_msg: "'prev_number', 'first_number', 'second_number' and 'sql_file' variables must be set."

- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}' Validate sequential order."
  ansible.builtin.assert:
    that:
      - first_number | int == prev_number | int
    fail_msg: "File {{ sql_file }} is out of sequence. Expected {{ prev_number }} but got {{ first_number }}."
  
- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}' Update previous number."
  ansible.builtin.set_fact:
    prev_number: "{{ second_number }}"

- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}' read file."
  ansible.builtin.slurp:
    src: "{{ file_path }}"
  register: sql_contents
  delegate_to: localhost

- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}' Fail if SQL file is empty."
  ansible.builtin.fail:
    msg: "SQL file '{{ sql_file }}' is empty."
  when: sql_contents.content | b64decode | trim == ''

- name: "({{db_schema}}) {{version}} Patch:'{{sql_file}}' Execute sql."
  community.postgresql.postgresql_query:
    search_path: "{{ db_schema }}"
    query: |
      BEGIN;

      {{ sql_contents.content | b64decode }};
      
      INSERT INTO schema_versions (revision, patch, description)
      VALUES (%(revision)s, %(patch)s, %(description)s)
      ON CONFLICT (revision)
      DO UPDATE SET
          patch       = EXCLUDED.patch,
          description = EXCLUDED.description,
          updated_at  = NOW();
      
      COMMIT;
    named_args:
      revision:    "{{ version }}"
      patch:       "{{ second_number }}"
      description: "Applied migrations up to {{ sql_file }}"